# 回测探索

在项目根目录安装依赖后打开本 Notebook（readme 中有 pip install 说明）。

In [1]:
from trading.baseline_builders import default_baseline_builders_v1
from trading.engine import run_scenarios
from trading.metrics import compare_portfolios
from trading.strategies.dca import DCAParams, fixed_weight_allocator, nasdaq_rule_allocator
from trading.viz import fig_equity_comparison, fig_summary_dashboard

params = DCAParams(
    symbols=("QQQ", "TQQQ"),
    start="2016-01-01",
    end="2026-01-01",
    monthly_budget=5000.0,
    default_weights={"QQQ": 0.7, "TQQQ": 0.3},
    signal_symbol="^IXIC",
    benchmark_symbol="QQQ",
)

results = run_scenarios(
    params,
    allocator=fixed_weight_allocator,
    baseline_builders=default_baseline_builders_v1(params.benchmark_symbol),
)
compare_portfolios(results)

,final_value,total_invested,total_return,CAGR,max_drawdown,volatility_annual,sharpe,sortino,calmar,start,...,years,fee_rate,slippage_rate,risk_trigger_count,avg_budget_utilization,Win Rate [%],Profit Factor,Expectancy,Omega Ratio,vs_baseline_final_ratio
scenario,,,,,,,,,,,,,,,,,,,,,
strategy,2.377934e+06,600000.0,2.963224,0.147789,-0.553139,0.289070,0.553420,0.656071,0.267183,2016-01-04,...,9.990418,0.0,0.0,0,1.0,NaN,NaN,NaN,1.132088,0.438610
monthly_full_QQQ,1.652939e+06,600000.0,1.754898,0.106758,-0.286562,0.150213,0.618480,0.747783,0.372548,2016-01-04,...,9.990418,0.0,0.0,0,NaN,NaN,NaN,NaN,1.164112,0.000000
lump_sum_first_day,6.603351e+06,600000.0,10.005586,0.271339,-0.677834,0.442795,0.721328,0.902861,0.400302,2016-01-04,...,9.990418,0.0,0.0,0,NaN,NaN,NaN,NaN,1.150679,2.994915
equal_weight_monthly,2.861264e+06,600000.0,3.768774,0.169246,-0.643476,0.358165,0.561203,0.666935,0.263018,2016-01-04,...,9.990418,0.0,0.0,0,NaN,NaN,NaN,NaN,1.130401,0.731016

In [2]:
fig_summary_dashboard(results).show()

In [3]:
fig_equity_comparison(results).show()

In [4]:
# 尝试纳指规则分配器
results_rule = run_scenarios(
    params,
    allocator=nasdaq_rule_allocator,
    baseline_builders=default_baseline_builders_v1(params.benchmark_symbol),
)
compare_portfolios(results_rule)

,final_value,total_invested,total_return,CAGR,max_drawdown,volatility_annual,sharpe,sortino,calmar,start,...,years,fee_rate,slippage_rate,risk_trigger_count,avg_budget_utilization,Win Rate [%],Profit Factor,Expectancy,Omega Ratio,vs_baseline_final_ratio
scenario,,,,,,,,,,,,,,,,,,,,,
strategy,2.341556e+06,600000.0,2.902593,0.146020,-0.536674,0.279169,0.557411,0.661128,0.272082,2016-01-04,...,9.990418,0.0,0.0,0,1.0,NaN,NaN,NaN,1.133316,0.416602
monthly_full_QQQ,1.652939e+06,600000.0,1.754898,0.106758,-0.286562,0.150213,0.618480,0.747783,0.372548,2016-01-04,...,9.990418,0.0,0.0,0,NaN,NaN,NaN,NaN,1.164112,0.000000
lump_sum_first_day,6.603351e+06,600000.0,10.005586,0.271339,-0.677834,0.442795,0.721328,0.902861,0.400302,2016-01-04,...,9.990418,0.0,0.0,0,NaN,NaN,NaN,NaN,1.150679,2.994915
equal_weight_monthly,2.861264e+06,600000.0,3.768774,0.169246,-0.643476,0.358165,0.561203,0.666935,0.263018,2016-01-04,...,9.990418,0.0,0.0,0,NaN,NaN,NaN,NaN,1.130401,0.731016